apiVersion: v2
name: mongodb-replicaset
description: A MongoDB replica set with configurable member count and post-deploy initialization job
type: application
version: 0.1.0
appVersion: "7.0"
icon: https://raw.githubusercontent.com/langazov/helm-charts/main/charts/mongodb-replicaset/icon.svg
keywords:
  - mongodb
  - replicaset
  - database
home: https://github.com/langazov/helm-charts
sources:
  - https://github.com/langazov/helm-charts
