apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-replicaset.headlessServiceName" . }}
  labels:
    {{- include "mongodb-replicaset.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: mongodb
      port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
  selector:
    {{- include "mongodb-replicaset.selectorLabels" . | nindent 4 }}
