{{- if not .Values.auth.existingKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-replicaset.keySecretName" . }}
  labels:
    {{- include "mongodb-replicaset.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "mongodb-replicaset.keyFileKey" . }}: {{ include "mongodb-replicaset.keyFileContent" . | b64enc | quote }}
{{- end }}
