{{- $count := include "mongodb-replicaset.effectiveReplicaCount" . | int -}}
{{- if and .Values.podDisruptionBudget.enabled (gt $count 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mongodb-replicaset.fullname" . }}
  labels:
    {{- include "mongodb-replicaset.labels" . | nindent 4 }}
spec:
  {{- $defaultMin := include "mongodb-replicaset.replicaSetMajority" $count | int }}
  minAvailable: {{ default $defaultMin .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "mongodb-replicaset.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongod
{{- end }}
