{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-replicaset.secretName" . }}
  labels:
    {{- include "mongodb-replicaset.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "mongodb-replicaset.rootPasswordKey" . | quote }}: {{ include "mongodb-replicaset.rootPassword" . | b64enc | quote }}
{{- end }}
