apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-replicaset.fullname" . }}
  labels:
    {{- include "mongodb-replicaset.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "mongodb-replicaset.selectorLabels" . | nindent 4 }}
