apiVersion: v2
name: phpmyadmin
description: A Helm chart for phpMyAdmin
type: application
version: 0.1.0
appVersion: "5.2.1"
maintainers:
  - name: emilo
    email: maintainer@example.com
keywords:
  - phpmyadmin
  - mysql
  - mariadb
  - database
  - admin
home: https://www.phpmyadmin.net/
sources:
  - https://github.com/phpmyadmin/phpmyadmin
