{{- $secretName := printf "%s-secrets" (include "wordpress.fullname" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ include "wordpress.name" . }}
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if and $existingSecret (not .Values.secrets.mariadb.rootPassword) }}
  mariadb-root-password: {{ index $existingSecret.data "mariadb-root-password" }}
  {{- else }}
  mariadb-root-password: {{ .Values.secrets.mariadb.rootPassword | default (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
  {{- if and $existingSecret (not .Values.secrets.mariadb.userPassword) }}
  mariadb-user-password: {{ index $existingSecret.data "mariadb-user-password" }}
  {{- else }}
  mariadb-user-password: {{ .Values.secrets.mariadb.userPassword | default (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
  {{- if and $existingSecret (not .Values.secrets.wordpress.adminPassword) }}
  wordpress-admin-password: {{ index $existingSecret.data "wordpress-admin-password" }}
  {{- else }}
  wordpress-admin-password: {{ .Values.secrets.wordpress.adminPassword | default (randAlphaNum 32) | b64enc | quote }}
  {{- end }}
  {{- if ne (default "" .Values.secrets.wordpress.smtpPassword) "" }}
  wordpress-smtp-password: {{ .Values.secrets.wordpress.smtpPassword | b64enc | quote }}
  {{- end }}
