{{- if and .Values.mariadb.enabled .Values.mariadb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gitea.fullname" . }}-mariadb-pvc
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
  {{- with .Values.mariadb.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.mariadb.persistence.accessMode }}
  {{- if .Values.mariadb.persistence.storageClassName }}
  storageClassName: {{ .Values.mariadb.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}
{{- end }}
