{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}-mariadb
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  type: {{ .Values.mariadb.service.type }}
  ports:
    - port: {{ .Values.mariadb.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
{{- end }}
