{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}-postgres
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
