apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-secrets
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ include "gitea.adminPassword" . | b64enc | quote }}
  secret-key: {{ include "gitea.secretKey" . | b64enc | quote }}
  internal-token-uri: {{ include "gitea.internalTokenUri" . | b64enc | quote }}
  {{- if .Values.mariadb.enabled }}
  mariadb-root-password: {{ include "gitea.mariadbRootPassword" . | b64enc | quote }}
  mariadb-user-password: {{ include "gitea.mariadbUserPassword" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgres.enabled }}
  postgres-password: {{ include "gitea.postgresPassword" . | b64enc | quote }}
  {{- end }}
